# -*- coding: utf-8 -*-
"""MODULO 2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LFnmDX6eiTWmeI92X-k6hzf5hClAIZJQ

**MODULO 2**

ESTRUTURA DE DADOS

LISTAS
"""

dia_02_saldo_inicial = 1000

dia_02_transacao_1 = 140
dia_02_transacao_2 = 220
dia_02_transacao_3 = 58.70

dia_02_saldo_final = dia_02_saldo_inicial + dia_02_transacao_1 + dia_02_transacao_2 + dia_02_transacao_3

print(dia_02_saldo_final)

"""**DEFINIÇÃO **"""

usuario_web = ['jessica nathalia', 'jessica.nathalia', 'jeje123']
print(usuario_web)
print(type(usuario_web))

idade = 26
saldo_em_conta = 28
usuario_loggedin = True

usuario_web = ['jessica nathali', idade, 'jessica.nathalia', 'jeje123', saldo_em_conta, usuario_loggedin]

print(usuario_web)
print(type(usuario_web))

"""**OPERAÇÃO**

concatenação*

Fabricantes de carros
"""

fabricantes_carros_alemanha = ['porsche', 'bmw', 'audi']
fabricantes_carros_eua = ['ford', 'gm',]
fabricantes_carros = fabricantes_carros_alemanha + fabricantes_carros_eua

print(fabricantes_alemanha)
print(fabricantes_eua)

"""fatiamento"""

print(f'0: {fabricantes_carros_alemanha[0]}')
print(f'0: {fabricantes_carros_eua[-1]}')

print(fabricantes_carros)

fabricantes_carros[0] = 'porsche'
print(fabricantes_carros)

"""METODOS"""

juros = [0.07, 0.14, 1.99, 0.08]
print(juros)

#inserir um elemento sem susbstituir: list.insert(index, val)
juros.insert(0, 0.10)
print(juros)

#inserir elemento no fim da lista: list.append(val)
juros.append(0.09)
print(juros)

# remover um elemento pelo valor: list.remove(val)
juros.remove(0.1)
print(juros)

# remover um elemento pelo indice: list.pop(val)
terceiro_juros = juros.pop(2)
print(terceiro_juros)

print(juros)

"""**CONVERSÃO**"""

email = 'wesllyoliveira77@icloud.com'
caracteres_email = list(email)

print(email)
print(caracteres_email)